# Generated by Django 5.1.6 on 2025-02-15 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_remove_payment_event_remove_payment_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendee',
            name='events',
        ),
        migrations.RemoveField(
            model_name='event',
            name='max_attendees',
        ),
        migrations.AddField(
            model_name='event',
            name='attendees',
            field=models.ManyToManyField(related_name='events', to='event.attendee'),
        ),
    ]
