# Generated by Django 5.1.6 on 2025-02-15 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_remove_attendee_events_remove_event_max_attendees_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='phone_no',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
