# Generated by Django 5.1.6 on 2025-03-04 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0011_alter_event_attendees_alter_event_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='max_attendees',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
